const statements = [
  `CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name TEXT UNIQUE NOT NULL,
    user_email TEXT,
    user_password TEXT NOT NULL,
    user_firstname TEXT,
    user_lastname TEXT,
    user_address TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS items (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id BIGINT,
    item_name TEXT,
    item_description TEXT,
    starting_price DOUBLE PRECISION,
    auction_start_time TIMESTAMPTZ,
    auction_end_time TIMESTAMPTZ,
    current_bid_amount DOUBLE PRECISION,
    item_picture TEXT,
    highest_price DOUBLE PRECISION,
    current_bidder_id BIGINT
  )`,
  `CREATE TABLE IF NOT EXISTS bids (
    bid_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bidder_id BIGINT,
    item_id BIGINT,
    bid_amount DOUBLE PRECISION,
    bid_time TIMESTAMPTZ
  )`,
  `CREATE TABLE IF NOT EXISTS orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT UNIQUE NOT NULL,
    user_id BIGINT NOT NULL,
    item_name TEXT NOT NULL,
    amount DOUBLE PRECISION,
    status TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS contact_form (
    contact_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_name TEXT,
    contact_email TEXT,
    contact_number TEXT,
    contact_message TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT,
    role_id BIGINT
  )`,
  "CREATE INDEX IF NOT EXISTS items_seller_id_idx ON items (seller_id)",
  "CREATE INDEX IF NOT EXISTS items_current_bidder_id_idx ON items (current_bidder_id)",
  "CREATE INDEX IF NOT EXISTS bids_item_id_bid_id_idx ON bids (item_id, bid_id DESC)",
  "CREATE INDEX IF NOT EXISTS orders_user_id_idx ON orders (user_id)",
];

module.exports = async (pool) => {
  for (const statement of statements) await pool.query(statement);
};
